Controls updated
GloireIrenge/glozik pull request #2
Opened 2024-07-11 13:02 UTC by GloireIrenge

This pull request comes with the following changes :
- Fixing the not working buttons
- updating the ui
- adding the not working image on the interface
- updating the README file

2024-07-12 14:23 UTC, mwafrika requested changes

2024-07-12 14:23 UTC, mwafrika commented on index.html
> +                    </div>
Kindly use semantic tags to ensure a more meaningful, accessible and maintainable web.
Example: main, section, aside, article, ...

2024-07-12 17:30 UTC, GloireIrenge commented
Thank you so much, let me do it

Le ven. 12 juil. 2024 à 16:23, MWAFRIKA MUFUNGIZI ***@***.***>
a écrit :

> ***@***.**** requested changes on this pull request.
> ------------------------------
>
> In index.html
> <https://github.com/GloireIrenge/glozik/pull/2#discussion_r1676004183>:
>
> > +    <div class="container mt-5">
> +        <div class="card text-center">
> +            <div class="card-header">
> +                GloPlayer
> +            </div>
> +            <div class="card-body">
> +                <img src="img/tomimage.jpg" class="card-img-top" alt="Gloplayer">
> +                <h5 class="card-title" id="song-title">No Song Playing</h5>
> +                <div class="audio-player">
> +                    <audio id="audio-player">
> +                        <source id="audio-source" src="" type="audio/mpeg">
> +                        Your browser does not support the audio element.
> +                    </audio>
> +                    <div class="controls">
> +                        <button id="prev-button" class="btn btn-primary" onclick="prevSong()">&#9664;</button>
> +                        <button id="play-pause-button" class="btn btn-primary" onclick="togglePlayPause()">&#9654;</button>
> +                        <button id="next-button" class="btn btn-primary" onclick="nextSong()">&#9654;</button>
> +                    </div>
> +                    <div class="progress mt-3">
> +                        <input type="range" id="progress-bar" value="0" min="0" max="100" step="1">
> +                    </div>
>
> Kindly use semantic tags to ensure a more meaningful, accessible and
> maintainable web.
> Example: main, section, aside, article, ...
>
> —
> Reply to this email directly, view it on GitHub
> <https://github.com/GloireIrenge/glozik/pull/2#pullrequestreview-2175028285>,
> or unsubscribe
> <https://github.com/notifications/unsubscribe-auth/AI6YO52TFM5RMQXTQPMUPRLZL7RGHAVCNFSM6AAAAABKW6F46KVHI2DSMVQWIX3LMV43YUDVNRWFEZLROVSXG5CSMV3GSZLXHMZDCNZVGAZDQMRYGU>
> .
> You are receiving this because you authored the thread.Message ID:
> ***@***.***>
>

2024-07-13 13:06 UTC, mwafrika approved these changes
🎊 🎊 💯 💯 Congratulations @GloireIrenge !!! your pull request is ready to be merged.

2024-07-13 14:47 UTC, GloireIrenge commented
Thank you so much for the great news!

Le sam. 13 juil. 2024 à 15:07, MWAFRIKA MUFUNGIZI ***@***.***>
a écrit :

> ***@***.**** approved this pull request.
>
> 🎊 🎊 💯 💯 Congratulations @GloireIrenge
> <https://github.com/GloireIrenge> !!! your pull request is ready to be
> merged.
>
> —
> Reply to this email directly, view it on GitHub
> <https://github.com/GloireIrenge/glozik/pull/2#pullrequestreview-2176250041>,
> or unsubscribe
> <https://github.com/notifications/unsubscribe-auth/AI6YO55JJTPD2MLPOY3SD5LZMEQ7PAVCNFSM6AAAAABKW6F46KVHI2DSMVQWIX3LMV43YUDVNRWFEZLROVSXG5CSMV3GSZLXHMZDCNZWGI2TAMBUGE>
> .
> You are receiving this because you were mentioned.Message ID:
> ***@***.***>
>

2024-07-13 18:06 UTC, merged